name: movies
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # SQLite
  sqflite: ^2.0.1
  path: ^1.8.0

  jiffy: ^4.1.0
  cupertino_icons: ^1.0.3
  scroll_snap_list: ^0.8.4

  json_serializable: ^6.0.1
  json_annotation: ^4.3.0

  # Provider
  # Version 4.1.3 doesn't have null safety, so --no-sound-null-safety has been added in "edit configurations"
  # Provider is used only in one place, the base_view to support the ViewModel Architecture.
  # Once all screens have been migrated to flutter_bloc we can delete the base_view and remove the provider library and "--no-sound-null-safety" from "edit configurations"
  provider: ^6.0.0

  # Flutter Bloc
  flutter_bloc: ^8.1.1

  # For comparing objects, "==" in flutter by default checks if two objects are the same instance
  # To use == to check if two objects are the same object but different instances we use the equatable library
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^7.1.3
  injectable: ^1.4.1

  # Http
  http: ^0.13.4
  dio: ^4.0.6

  # Google Fonts
  google_fonts: ^2.1.0
  flutter_secure_storage: ^7.0.1

dev_dependencies:
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  injectable_generator:


# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
